# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HSV_Checker_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QColor

class _Bar(QtWidgets.QWidget):
    clickedValue = QtCore.pyqtSignal(int)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


        self._bar_solid_percent = 0.8
        self._background_color = QtGui.QColor('black')
        self._padding = 4.0  # n-pixel gap around edge.
        self.value = 50

    def paintEvent(self, e):
        painter = QtGui.QPainter(self)
        brush = QtGui.QBrush()
        brush.setColor(self._background_color)
        brush.setStyle(Qt.SolidPattern)
        print(painter.device().width())
        rect = QtCore.QRect(0, 0, painter.device().width(), painter.device().height())
        painter.fillRect(rect, brush)
        painter.end()

    def _trigger_refresh(self):
        self.update()

    def setValue(self, value):
        self.value = value
        self.update()

    def setColor(self, color):
        self.steps = [color] * self._bar.n_steps
        self.update()

    def setColors(self, colors):
        self.n_steps = len(colors)
        self.steps = colors
        self.update()

    def setColors_gradation(self, startRgbList, endRgbList, nSteps):
        self.n_steps = nSteps
        colors = []
        dRgb = [endRgbList[0] - startRgbList[0], endRgbList[1] - startRgbList[1], endRgbList[2] - startRgbList[2]]
        for i in range(nSteps):
            colors.append([startRgbList[0] + dRgb[0]/nSteps*i, startRgbList[1] + dRgb[1]/nSteps*i, startRgbList[2] + dRgb[2]/nSteps*i])
        self.steps = colors
        self.update()

    def setBarSolidPercent(self, f):
        self._bar_solid_percent = float(f)
        self.update()

    def setBackgroundColor(self, color):
        self._background_color = QtGui.QColor(color)
        self.update()
    def setNotchesVisible(self, b):
        return self._dial.setNotchesVisible(b)

class Ui_Form(QtWidgets.QWidget):
    def __init__(self, Form):
        super().__init__()
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.colorDisplay = _Bar()
        self.colorDisplay.setBarSolidPercent(0.9)
        self.colorDisplay.setBackgroundColor('gray')
        self.colorDisplay.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorDisplay.sizePolicy().hasHeightForWidth())
        self.colorDisplay.setSizePolicy(sizePolicy)
        self.colorDisplay.setObjectName("colorDisplay")
        self.horizontalLayout_2.addWidget(self.colorDisplay)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hueLabel = QtWidgets.QLabel(Form)
        self.hueLabel.setObjectName("hueLabel")
        self.horizontalLayout_3.addWidget(self.hueLabel)
        self.hueValue = QtWidgets.QLabel(Form)
        self.hueValue.setObjectName("hueValue")
        self.horizontalLayout_3.addWidget(self.hueValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.hueSlider = QtWidgets.QSlider(Form)
        self.hueSlider.setMaximum(360)
        self.hueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hueSlider.setObjectName("hueSlider")
        self.verticalLayout_2.addWidget(self.hueSlider)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.satLabel = QtWidgets.QLabel(Form)
        self.satLabel.setObjectName("satLabel")
        self.horizontalLayout_4.addWidget(self.satLabel)
        self.satValue = QtWidgets.QLabel(Form)
        self.satValue.setObjectName("satValue")
        self.horizontalLayout_4.addWidget(self.satValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.satSlider = QtWidgets.QSlider(Form)
        self.satSlider.setMaximum(255)
        self.satSlider.setOrientation(QtCore.Qt.Horizontal)
        self.satSlider.setObjectName("satSlider")
        self.satSlider.setValue(255)
        self.verticalLayout_2.addWidget(self.satSlider)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.valueValue = QtWidgets.QLabel(Form)
        self.valueValue.setObjectName("valueValue")
        self.horizontalLayout_5.addWidget(self.valueValue)
        self.valueLabel = QtWidgets.QLabel(Form)
        self.valueLabel.setObjectName("valueLabel")
        self.horizontalLayout_5.addWidget(self.valueLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.valueSlider = QtWidgets.QSlider(Form)
        self.valueSlider.setMaximum(255)
        self.valueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.valueSlider.setObjectName("valueSlider")
        self.valueSlider.setValue(255)
        self.verticalLayout_2.addWidget(self.valueSlider)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.hueSlider.valueChanged['int'].connect(self.hueValue.setNum)
        self.satSlider.valueChanged['int'].connect(self.satValue.setNum)
        self.valueSlider.valueChanged['int'].connect(self.valueValue.setNum)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.color = QColor()
        self.color.setHsv(0,255,255)
        self.colorDisplay.setBackgroundColor(self.color)

        self.hueSlider.valueChanged['int'].connect(self.colorChanged)
        self.satSlider.valueChanged['int'].connect(self.colorChanged)
        self.valueSlider.valueChanged['int'].connect(self.colorChanged)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hueLabel.setText(_translate("Form", "Hue"))
        self.hueValue.setText(_translate("Form", "0"))
        self.satLabel.setText(_translate("Form", "Saturation"))
        self.satValue.setText(_translate("Form", "255"))
        self.valueValue.setText(_translate("Form", "Value"))
        self.valueLabel.setText(_translate("Form", "255"))

    def colorChanged(self):
        self.color.setHsv(self.hueSlider.value(), self.satSlider.value(), self.valueSlider.value())
        self.colorDisplay.setBackgroundColor(self.color)

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form(Form)
    Form.show()
    sys.exit(app.exec_())
