# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hueLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hueLabel.sizePolicy().hasHeightForWidth())
        self.hueLabel.setSizePolicy(sizePolicy)
        self.hueLabel.setObjectName("hueLabel")
        self.horizontalLayout_3.addWidget(self.hueLabel)
        self.hueSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hueSpinBox.sizePolicy().hasHeightForWidth())
        self.hueSpinBox.setSizePolicy(sizePolicy)
        self.hueSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.hueSpinBox.setMaximum(360)
        self.hueSpinBox.setObjectName("hueSpinBox")
        self.horizontalLayout_3.addWidget(self.hueSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.hueSlider = QtWidgets.QSlider(self.centralwidget)
        self.hueSlider.setMaximum(360)
        self.hueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hueSlider.setObjectName("hueSlider")
        self.verticalLayout_2.addWidget(self.hueSlider)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.satLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.satLabel.sizePolicy().hasHeightForWidth())
        self.satLabel.setSizePolicy(sizePolicy)
        self.satLabel.setObjectName("satLabel")
        self.horizontalLayout_4.addWidget(self.satLabel)
        self.satSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.satSpinBox.sizePolicy().hasHeightForWidth())
        self.satSpinBox.setSizePolicy(sizePolicy)
        self.satSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.satSpinBox.setMaximum(255)
        self.satSpinBox.setProperty("value", 255)
        self.satSpinBox.setObjectName("satSpinBox")
        self.horizontalLayout_4.addWidget(self.satSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.satSlider = QtWidgets.QSlider(self.centralwidget)
        self.satSlider.setMaximum(255)
        self.satSlider.setProperty("value", 255)
        self.satSlider.setOrientation(QtCore.Qt.Horizontal)
        self.satSlider.setObjectName("satSlider")
        self.verticalLayout_2.addWidget(self.satSlider)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.valueValue = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valueValue.sizePolicy().hasHeightForWidth())
        self.valueValue.setSizePolicy(sizePolicy)
        self.valueValue.setObjectName("valueValue")
        self.horizontalLayout_5.addWidget(self.valueValue)
        self.valueSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valueSpinBox.sizePolicy().hasHeightForWidth())
        self.valueSpinBox.setSizePolicy(sizePolicy)
        self.valueSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valueSpinBox.setMaximum(255)
        self.valueSpinBox.setProperty("value", 255)
        self.valueSpinBox.setObjectName("valueSpinBox")
        self.horizontalLayout_5.addWidget(self.valueSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.valueSlider = QtWidgets.QSlider(self.centralwidget)
        self.valueSlider.setMaximum(255)
        self.valueSlider.setProperty("value", 255)
        self.valueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.valueSlider.setObjectName("valueSlider")
        self.verticalLayout_2.addWidget(self.valueSlider)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nStepsLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nStepsLabel.sizePolicy().hasHeightForWidth())
        self.nStepsLabel.setSizePolicy(sizePolicy)
        self.nStepsLabel.setObjectName("nStepsLabel")
        self.horizontalLayout.addWidget(self.nStepsLabel)
        self.stepSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepSpinBox.sizePolicy().hasHeightForWidth())
        self.stepSpinBox.setSizePolicy(sizePolicy)
        self.stepSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.stepSpinBox.setMinimum(1)
        self.stepSpinBox.setMaximum(200)
        self.stepSpinBox.setObjectName("stepSpinBox")
        self.horizontalLayout.addWidget(self.stepSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.nStepsSlider = QtWidgets.QSlider(self.centralwidget)
        self.nStepsSlider.setMinimum(1)
        self.nStepsSlider.setMaximum(50)
        self.nStepsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.nStepsSlider.setObjectName("nStepsSlider")
        self.verticalLayout_2.addWidget(self.nStepsSlider)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setHorizontalSpacing(11)
        self.gridLayout.setVerticalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.prese_color_20 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_20.sizePolicy().hasHeightForWidth())
        self.prese_color_20.setSizePolicy(sizePolicy)
        self.prese_color_20.setStyleSheet("background-color: rgb(255, 216, 177);\n"
"color: rgb(255, 216, 177);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1;\n"
"border-radius:10px;")
        self.prese_color_20.setObjectName("prese_color_20")
        self.gridLayout.addWidget(self.prese_color_20, 9, 2, 1, 1)
        self.prese_color_8 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_8.sizePolicy().hasHeightForWidth())
        self.prese_color_8.setSizePolicy(sizePolicy)
        self.prese_color_8.setStyleSheet("background-color: rgb(230, 25, 75);\n"
"color: rgb(230, 25, 75);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1px;\n"
"border-radius:10px;")
        self.prese_color_8.setObjectName("prese_color_8")
        self.gridLayout.addWidget(self.prese_color_8, 3, 0, 1, 1)
        self.prese_color_16 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_16.sizePolicy().hasHeightForWidth())
        self.prese_color_16.setSizePolicy(sizePolicy)
        self.prese_color_16.setStyleSheet("background-color: rgb(145, 30, 180);\n"
"color: rgb(145, 30, 180);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1;\n"
"border-radius:10px;")
        self.prese_color_16.setObjectName("prese_color_16")
        self.gridLayout.addWidget(self.prese_color_16, 4, 5, 1, 1)
        self.prese_color_7 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_7.sizePolicy().hasHeightForWidth())
        self.prese_color_7.setSizePolicy(sizePolicy)
        self.prese_color_7.setStyleSheet("background-color: rgb(245, 130, 49);\n"
"color: rgb(245, 130, 49);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1px;\n"
"border-radius:10px;")
        self.prese_color_7.setObjectName("prese_color_7")
        self.gridLayout.addWidget(self.prese_color_7, 3, 2, 1, 1)
        self.prese_color_17 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_17.sizePolicy().hasHeightForWidth())
        self.prese_color_17.setSizePolicy(sizePolicy)
        self.prese_color_17.setStyleSheet("background-color: rgb(193, 64, 244);\n"
"color: rgb(193, 64, 244);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1;\n"
"border-radius:10px;")
        self.prese_color_17.setObjectName("prese_color_17")
        self.gridLayout.addWidget(self.prese_color_17, 4, 8, 1, 1)
        self.prese_color_19 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_19.sizePolicy().hasHeightForWidth())
        self.prese_color_19.setSizePolicy(sizePolicy)
        self.prese_color_19.setStyleSheet("background-color: rgb(250, 190, 212);\n"
"color: rgb(250, 190, 212);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1;\n"
"border-radius:10px;")
        self.prese_color_19.setObjectName("prese_color_19")
        self.gridLayout.addWidget(self.prese_color_19, 9, 0, 1, 1)
        self.prese_color_6 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_6.sizePolicy().hasHeightForWidth())
        self.prese_color_6.setSizePolicy(sizePolicy)
        self.prese_color_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1;\n"
"border-radius:10px;")
        self.prese_color_6.setObjectName("prese_color_6")
        self.gridLayout.addWidget(self.prese_color_6, 2, 9, 1, 1)
        self.prese_color_18 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_18.sizePolicy().hasHeightForWidth())
        self.prese_color_18.setSizePolicy(sizePolicy)
        self.prese_color_18.setStyleSheet("background-color:rgb(240, 50, 230);\n"
"color: rgb(240, 50, 230);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1;\n"
"border-radius:10px;")
        self.prese_color_18.setObjectName("prese_color_18")
        self.gridLayout.addWidget(self.prese_color_18, 4, 9, 1, 1)
        self.prese_color_14 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_14.sizePolicy().hasHeightForWidth())
        self.prese_color_14.setSizePolicy(sizePolicy)
        self.prese_color_14.setStyleSheet("background-color: rgb(66, 212, 244);\n"
"color: rgb(66, 212, 244);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1px;\n"
"border-radius:10px;")
        self.prese_color_14.setObjectName("prese_color_14")
        self.gridLayout.addWidget(self.prese_color_14, 4, 2, 1, 1)
        self.prese_color_11 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_11.sizePolicy().hasHeightForWidth())
        self.prese_color_11.setSizePolicy(sizePolicy)
        self.prese_color_11.setStyleSheet("background-color: rgb(60, 180, 75);\n"
"color: rgb(60, 180, 75);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1px;\n"
"border-radius:10px;")
        self.prese_color_11.setObjectName("prese_color_11")
        self.gridLayout.addWidget(self.prese_color_11, 3, 8, 1, 1)
        self.prese_color_10 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_10.sizePolicy().hasHeightForWidth())
        self.prese_color_10.setSizePolicy(sizePolicy)
        self.prese_color_10.setStyleSheet("background-color: rgb(255, 225, 25);\n"
"color: rgb(255, 225, 25);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1px;\n"
"border-radius:10px;")
        self.prese_color_10.setObjectName("prese_color_10")
        self.gridLayout.addWidget(self.prese_color_10, 3, 4, 1, 1)
        self.prese_color_9 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_9.sizePolicy().hasHeightForWidth())
        self.prese_color_9.setSizePolicy(sizePolicy)
        self.prese_color_9.setStyleSheet("background-color: rgb(191, 239, 69);\n"
"color: rgb(191, 239, 69);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1px;\n"
"border-radius:10px;")
        self.prese_color_9.setObjectName("prese_color_9")
        self.gridLayout.addWidget(self.prese_color_9, 3, 5, 1, 1)
        self.prese_color_12 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_12.sizePolicy().hasHeightForWidth())
        self.prese_color_12.setSizePolicy(sizePolicy)
        self.prese_color_12.setStyleSheet("background-color:rgb(35, 120, 82);\n"
"color: rgb(35, 120, 82);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1px;\n"
"border-radius:10px;")
        self.prese_color_12.setObjectName("prese_color_12")
        self.gridLayout.addWidget(self.prese_color_12, 3, 9, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1px;\n"
"border-radius:10px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 9, 9, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("background-color: rgb(255, 250, 200);\n"
"color: rgb(255, 250, 200);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1px;\n"
"border-radius:10px;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 9, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 255, 195);\n"
"color: rgb(170, 255, 195);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1px;\n"
"border-radius:10px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 9, 5, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("background-color: rgb(220, 190, 255);\n"
"color: rgb(220, 190, 255);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1px;\n"
"border-radius:10px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 9, 8, 1, 1)
        self.prese_color_13 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_13.sizePolicy().hasHeightForWidth())
        self.prese_color_13.setSizePolicy(sizePolicy)
        self.prese_color_13.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"color: rgb(0, 255, 255);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1;\n"
"border-radius:10px;")
        self.prese_color_13.setObjectName("prese_color_13")
        self.gridLayout.addWidget(self.prese_color_13, 4, 0, 1, 1)
        self.prese_color_3 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_3.sizePolicy().hasHeightForWidth())
        self.prese_color_3.setSizePolicy(sizePolicy)
        self.prese_color_3.setStyleSheet("background-color: rgb(128, 128, 0);\n"
"color: rgb(128, 128, 0);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1;\n"
"border-radius:10px;")
        self.prese_color_3.setObjectName("prese_color_3")
        self.gridLayout.addWidget(self.prese_color_3, 2, 4, 1, 1)
        self.prese_color_4 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_4.sizePolicy().hasHeightForWidth())
        self.prese_color_4.setSizePolicy(sizePolicy)
        self.prese_color_4.setStyleSheet("background-color: rgb(70, 153, 144);\n"
"color: rgb(70, 153, 144);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1;\n"
"border-radius:10px;")
        self.prese_color_4.setObjectName("prese_color_4")
        self.gridLayout.addWidget(self.prese_color_4, 2, 5, 1, 1)
        self.prese_color_2 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_2.sizePolicy().hasHeightForWidth())
        self.prese_color_2.setSizePolicy(sizePolicy)
        self.prese_color_2.setStyleSheet("background-color: rgb(154, 99, 36);\n"
"color:rgb(154, 99, 36);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1;\n"
"border-radius:10px;\n"
"")
        self.prese_color_2.setObjectName("prese_color_2")
        self.gridLayout.addWidget(self.prese_color_2, 2, 2, 1, 1)
        self.prese_color_5 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_5.sizePolicy().hasHeightForWidth())
        self.prese_color_5.setSizePolicy(sizePolicy)
        self.prese_color_5.setStyleSheet("background-color: rgb(0, 0, 117);\n"
"color: rgb(0, 0, 117);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1;\n"
"border-radius:10px;")
        self.prese_color_5.setObjectName("prese_color_5")
        self.gridLayout.addWidget(self.prese_color_5, 2, 8, 1, 1)
        self.prese_color_1 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_1.sizePolicy().hasHeightForWidth())
        self.prese_color_1.setSizePolicy(sizePolicy)
        self.prese_color_1.setStyleSheet("background-color: rgb(128, 0, 0);\n"
"color: rgb(128, 0, 0);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1;\n"
"border-radius:10px;")
        self.prese_color_1.setCheckable(False)
        self.prese_color_1.setObjectName("prese_color_1")
        self.gridLayout.addWidget(self.prese_color_1, 2, 0, 1, 1)
        self.prese_color_15 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prese_color_15.sizePolicy().hasHeightForWidth())
        self.prese_color_15.setSizePolicy(sizePolicy)
        self.prese_color_15.setStyleSheet("background-color: rgb(67, 99, 216);\n"
"color: rgb(67, 99, 216);\n"
"border-color: rgb(67, 67, 67);\n"
"border-style: solid;\n"
"border-width:1px;\n"
"border-radius:10px;")
        self.prese_color_15.setObjectName("prese_color_15")
        self.gridLayout.addWidget(self.prese_color_15, 4, 4, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hueLabel.setText(_translate("MainWindow", "Hue"))
        self.satLabel.setText(_translate("MainWindow", "Saturation"))
        self.valueValue.setText(_translate("MainWindow", "Value"))
        self.nStepsLabel.setText(_translate("MainWindow", "Steps"))
        self.prese_color_20.setToolTip(_translate("MainWindow", "Apricot"))
        self.prese_color_20.setText(_translate("MainWindow", "#ffd8b1"))
        self.prese_color_8.setToolTip(_translate("MainWindow", "Red"))
        self.prese_color_8.setText(_translate("MainWindow", "#e6194B"))
        self.prese_color_16.setToolTip(_translate("MainWindow", "Purple"))
        self.prese_color_16.setText(_translate("MainWindow", "#911eb4"))
        self.prese_color_7.setToolTip(_translate("MainWindow", "Orange"))
        self.prese_color_7.setText(_translate("MainWindow", "#f58231"))
        self.prese_color_17.setToolTip(_translate("MainWindow", "Violet"))
        self.prese_color_17.setText(_translate("MainWindow", "#c140f4"))
        self.prese_color_19.setToolTip(_translate("MainWindow", "Pink"))
        self.prese_color_19.setText(_translate("MainWindow", "#fabed4"))
        self.prese_color_6.setToolTip(_translate("MainWindow", "Black"))
        self.prese_color_6.setText(_translate("MainWindow", "#000000"))
        self.prese_color_18.setToolTip(_translate("MainWindow", "Magenta"))
        self.prese_color_18.setText(_translate("MainWindow", "#f032e6"))
        self.prese_color_14.setToolTip(_translate("MainWindow", "Cerulean"))
        self.prese_color_14.setText(_translate("MainWindow", "#42d4f4"))
        self.prese_color_11.setToolTip(_translate("MainWindow", "Green"))
        self.prese_color_11.setText(_translate("MainWindow", "#3cb44b"))
        self.prese_color_10.setToolTip(_translate("MainWindow", "Yellow"))
        self.prese_color_10.setText(_translate("MainWindow", "#ffe119"))
        self.prese_color_9.setToolTip(_translate("MainWindow", "Lime"))
        self.prese_color_9.setText(_translate("MainWindow", "#bfef45"))
        self.prese_color_12.setToolTip(_translate("MainWindow", "Turtle Green"))
        self.prese_color_12.setText(_translate("MainWindow", "#237852"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "White"))
        self.pushButton_4.setText(_translate("MainWindow", "#ffffff"))
        self.pushButton.setToolTip(_translate("MainWindow", "Beige"))
        self.pushButton.setText(_translate("MainWindow", "#fffac8"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "Mint"))
        self.pushButton_2.setText(_translate("MainWindow", "#aaffc3"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "Lavender"))
        self.pushButton_3.setText(_translate("MainWindow", "#dcbeff"))
        self.prese_color_13.setToolTip(_translate("MainWindow", "Cyan"))
        self.prese_color_13.setText(_translate("MainWindow", "#00ffff"))
        self.prese_color_3.setToolTip(_translate("MainWindow", "Olive"))
        self.prese_color_3.setText(_translate("MainWindow", "#808000"))
        self.prese_color_4.setToolTip(_translate("MainWindow", "Teal"))
        self.prese_color_4.setText(_translate("MainWindow", "#469990"))
        self.prese_color_2.setToolTip(_translate("MainWindow", "Brown"))
        self.prese_color_2.setText(_translate("MainWindow", "#9A6324"))
        self.prese_color_5.setToolTip(_translate("MainWindow", "Navy"))
        self.prese_color_5.setText(_translate("MainWindow", "#000075"))
        self.prese_color_1.setToolTip(_translate("MainWindow", "Maroon"))
        self.prese_color_1.setText(_translate("MainWindow", "#800000"))
        self.prese_color_15.setToolTip(_translate("MainWindow", "Blue"))
        self.prese_color_15.setText(_translate("MainWindow", "#4363d8"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QMainWindow()
    window = Ui_MainWindow()
    window.setupUi(main)
    main.show()
    from Ui_Functions import Ui_Functions
    functions = Ui_Functions(window)

    sys.exit(app.exec_())
else:
    print(__name__, "hh")
# press ctrl+b in sublime to run